### PR TITLE
Feature/email notifications

### PR DESCRIPTION
**Pull request by akinsey**
Adds email thread notifications:

Please checkout epoch project on the same branch and run the migration prior to testing.

1) Ensure that when there is a reply to a thread you've created you receive an email for every reply.

2) Ensure that when there is a reply to a thread that you have replied to, you receive one email notification. If you reply to the thread again, you should again only receive an email notification about the next reply.

3) Ensure that Settings page has the new subscription settings and that they work properly

### CODE REVIEW

**Comment by unenglishable** [comment]
i'm on it 👍

**Comment by unenglishable** [comment]
thread owner reply notifications are good!

**Comment by unenglishable** [comment]
thread replier single notifications are good the first time, and consecutive times (when replying again and receiving a single notification on reply)

**Comment by unenglishable** [comment]
can't find the subscriptions management!  where is it?

**Comment by unenglishable** [comment]
ah okay, nvm i got it.  i thought it was admin settings, but it is under user settings 😅

**Comment by akinsey** [comment]
Resolves #336

**Comment by akinsey** [comment]
@unenglishable I'd argue that we don't need to go into that much detail, for the most part the thread will die off and the user will stop receiving the emails. Providing that information might just confuse the user more.

Alternatively, should we just automatically delete all past subscriptions when switching them off?

**Comment by unenglishable** [comment]
@akinsey iirc, old forums had a button that you could use to manually subscribe to the thread.

**Comment by unenglishable** [comment]
@akinsey  yes, good point about the thread dying off.  if i think about it that way, a few different ideas come to mind.  lmk what you think, mostly just throwing this stuff out there; if you think it's good for now, we can finish the merge.  otherwise, if some of this sounds good and isn't too difficult, we can do it in this PR too.

iirc, old forums had a button that you could use to manually subscribe to the thread.
that button could also be used to unsubscribe.

since we're doing auto subscription, this button could serve these purposes:

* the button would be a good way to let other users to subscribe to "all updates" for the thread

* the button would allow the OP to unsubscribe from "all updates"

if we have this button, it might be fine to get rid of the "Enable Thread Notifications" setting.  and i suppose you could keep the one for purging all subscriptions.

if you get rid of "Enable Thread Notifications", you could add a UI notification/banner to the thread posting flow that notifies the user they have been subscribed, and give them the option to unsubscribe if they want to.


overall:

i think anything that could make the subscription behaviour more predictable and transparent would be good.  the current behaviour is a little confusing if the user doesn't know exactly how it works.  for example, if i created a thread, how could i unsubscribe from notifications for just that one thread?  of course, you could argue that a user wouldn't want to do that, but i'm saying if they did, should make it easy.

if we want to make the thread subscriptions system "good", we should spend time later designing it.   ¯\_(ツ)_/¯

**Comment by akinsey** [comment]
We should meet and implement something like that, as it seems useful. Might be confused with "watching" a thread or board though. @unenglishable

**Pull request merged**
