### PR TITLE
Fix post lock auth

### LINKED ISSUE #711: Allow mods/admins to perform mod actions while post is locked
Fix for this would be in the authorization code for post update.

### PR DESCRIPTION
**Pull request by akinsey**
Fixes #711

Also fixes a bug with global mods not being able to hide/unhide locked posts
Tests will pass once previous merges api test issue is resolved.

### CODE REVIEW

**Comment by akinsey** [comment]
Fixes #715

**Comment by unenglishable** [comment]
re-submit this for merge into board-edit-lock 👍

**Comment by unenglishable** [comment]
OR rebase

**Comment by unenglishable** [comment]
nvm don't rebase lol

**Pull request merged**
